bayesimpact/bayes-developer-setup

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/15) &emsp; Multiple assignees:&emsp;<img alt="@dedan" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/196905?s=40&v=3">&nbsp;<a href="/bayesimpact/bayes-developer-setup/pulls/assigned/dedan">dedan</a>,&emsp;<img alt="@florianjourda" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/4361853?s=40&v=3">&nbsp;<a href="/bayesimpact/bayes-developer-setup/pulls/assigned/florianjourda">florianjourda</a>
=> Make install.sh work for other shells, especially zsh.

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/23) &emsp; Multiple assignees:&emsp;<img alt="@dedan" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/196905?s=40&v=3">&nbsp;<a href="/bayesimpact/bayes-developer-setup/pulls/assigned/dedan">dedan</a>,&emsp;<img alt="@florianjourda" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/4361853?s=40&v=3">&nbsp;<a href="/bayesimpact/bayes-developer-setup/pulls/assigned/florianjourda">florianjourda</a>
=> Ignore editor temp files.

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/21) &emsp; Multiple assignees:&emsp;<img alt="@dedan" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/196905?s=40&v=3">&nbsp;<a href="/bayesimpact/bayes-developer-setup/pulls/assigned/dedan">dedan</a>,&emsp;<img alt="@florianjourda" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/4361853?s=40&v=3">&nbsp;<a href="/bayesimpact/bayes-developer-setup/pulls/assigned/florianjourda">florianjourda</a>
=> Show the reviewable.io URL instead of the GitHub one.

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/16) &emsp; Multiple assignees:&emsp;<img alt="@dedan" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/196905?s=40&v=3">&nbsp;<a href="/bayesimpact/bayes-developer-setup/pulls/assigned/dedan">dedan</a>,&emsp;<img alt="@pcorpet" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/7937848?s=40&v=3">&nbsp;<a href="/bayesimpact/bayes-developer-setup/pulls/assigned/pcorpet">pcorpet</a>
=> Fix Docker registry login on OSX

git-custom-commands-test/features/git-submit.feature, git-custom-commands-test/features/steps.rb, git-custom-commands-test/features/support/env.rb
+@florianjourda
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/30) &emsp; Multiple assignees:&emsp;<img alt="@dedan" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/196905?s=40&v=3">&nbsp;<a href="/bayesimpact/bayes-developer-setup/pulls/assigned/dedan">dedan</a>,&emsp;<img alt="@florianjourda" height="20" width="20" align="absmiddle" src="https://avatars.githubusercontent.com/u/4361853?s=40&v=3">&nbsp;<a href="/bayesimpact/bayes-developer-setup/pulls/assigned/florianjourda">florianjourda</a>
=> Add first tests for `git submit`.

git-custom-commands-test/features/git-submit.feature, git-custom-commands-test/features/steps.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/31)
=> Add git submit test scenarios when local repo is late compared to origin/master.

.gitignore, README.md, circle.yml, docker-compose.yml, reviewable/.eslintrc.json, reviewable/Dockerfile, reviewable/README.md, reviewable/lgtm_plus_resolved_discussions.js, reviewable/package.json, reviewable/test/lgtm_plus_resolved_discussions_spec.js
+@pcorpet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/36)
=> Implement a custom reviewable rule

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/38)
=> Install a recent version of hub if needed.

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/39)
=> Revert to a stable version of hub

reviewable/lgtm_plus_resolved_discussions.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/40)
=> Also accept an LGTM-strong as an approval.

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/41)
=> Abort before sending an empty PR.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/42)
=> Ensures that the Continous Integration is successful before submitting.

install.sh
+@pcorpet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/45)
=> Fix the `hub` install script on macOS

bin/git-review, install.sh
+@pcorpet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/46)
=> Update `hub` version aaaaand ‘automated reviewer assignment’ Fix the `hub` install script on macOS

install.sh
+@dedan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/48)
=> Use a folder that exists on all machines, not only dedan's :-)

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/51)
=> Add a -f flag to `git review` to push-force a local change to the remote repo.

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/52)
=> Give REMOTE_BRANCH env variable for the git-review hook.

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/53)
=> Use existing remote branch if any instead before creating a new one.

README.md, install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/54)
=> adds instruction to the readme for logging into github before installation.

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/55)
=> Do not use master as a remote branch even if already linked.

README.md
Update bash and hub instructionswq
Respond to CR feedback
Update rebase instructions
Add instructions for use
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/59)
=> Update bash update instructions

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/61)
=> Fixes #58: complain when trying to create a branch using an empty username.

git-submit.bash_completion
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/62)
=> Add Bash completion for git-submit (complete branches names).

.gitignore, common-installs/github_tools.sh, common-installs/mac_setup.sh, install.sh
Add docker.
Add more crazy tools !
Update mac packages install.
Add mac_setup.sh
Use homebrew.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/63)
=> Add tools and update hub version.

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/64)
=> Fix redirect issue and update version.

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/66)
=> Make hub command interactive.

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/67)
=> Add command.

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/69)
=> Update PATH while installing so that hub is accessible during the install as well.

.gitignore
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/71)
=> Update gitignore with more files that are downloaded during install.

bin/git-review
test #
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/74)
=> Rename git review if hash in branch name

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/80)
=> Avoid more forbidden chars in remote branch names.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/85)
=> Introduce a new experimental way to submit by using the Merge API.

docker-compose.yml, lambda-reviewable-to-slack/reviewable_to_slack.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/88)
=> Read constant from env vars for reviewable-to-slack integration

lambda-reviewable-to-slack/reviewable_to_slack.py, lambda-reviewable-to-slack/reviewable_to_slack_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/89)
=> Allow to select which slack users get reviewable notification

lambda-reviewable-to-slack/zappa_settings.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/91)
=> Rename lambda function for reviewable-to-slack and remove debugging from prod

lambda-reviewable-to-slack/reviewable_to_slack.py, lambda-reviewable-to-slack/reviewable_to_slack_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/92)
=> Use comments instead of status to detect lgtm

lambda-reviewable-to-slack/reviewable_to_slack.py, lambda-reviewable-to-slack/reviewable_to_slack_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/93)
=> Display comments from reviewable in slack integration

lambda-reviewable-to-slack/reviewable_to_slack.py, lambda-reviewable-to-slack/reviewable_to_slack_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/94)
=> Use Slack app bot instead of Zappier to post on Slack

lambda-reviewable-to-slack/reviewable_to_slack.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/96)
=> Ignore reviewable notification that have no pull request ready

lambda-reviewable-to-slack/reviewable_to_slack.py, lambda-reviewable-to-slack/reviewable_to_slack_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/95)
=> Ignore Reviewable notification on master

lambda-reviewable-to-slack/reviewable_to_slack.py, lambda-reviewable-to-slack/reviewable_to_slack_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/97)
=> Warn issue owner on slack when tests are fixed

lambda-reviewable-to-slack/reviewable_to_slack.py, lambda-reviewable-to-slack/reviewable_to_slack_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/99)
=> Accept github user names with dash in reviewable-to-slack integration

lambda-reviewable-to-slack/reviewable_to_slack.py, lambda-reviewable-to-slack/reviewable_to_slack_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/100)
=> Do not ping reviewers in Slack after they gave a lgtm

lambda-reviewable-to-slack/reviewable_to_slack.py, lambda-reviewable-to-slack/reviewable_to_slack_test.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/102)
=> Tell reviewee when they are unaddressed comments

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/103)
=> Update master locally when using the experimental version of git-submit as well.

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/107)
=> Add reviewrs to git-review

.circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/109)
=> Fix CI to make sure it can run several builds on the same host.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/110)
=> Escape special chars in branch name when searching corresponding pull request.

bin/git-submit, git-custom-commands-test/features/git-submit.feature
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/111)
=> Enable the "Squash on GitHub" feature by default.

reviewable/lgtm_plus_resolved_discussions.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/112)
=> Accept LGTMs from rquested reviewers even if they are not assignees.

docker-compose.yml, reviewable/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/113)
=> Update node version for reviewable script and make it easier to test locally.

reviewable/lgtm_plus_resolved_discussions.js, reviewable/test/lgtm_plus_resolved_discussions_spec.js
See https://github.com/Reviewable/Reviewable/issues/510.
Update node version for reviewable script and make it easier to test locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/114)
=> Account for new statuses

reviewable/lgtm_plus_resolved_discussions.js, reviewable/test/lgtm_plus_resolved_discussions_spec.js
Account for new statuses
See https://github.com/Reviewable/Reviewable/issues/510.
Update node version for reviewable script and make it easier to test locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/115)
=> Show unresolved discussion's target in the description.

reviewable/lgtm_plus_resolved_discussions.js, reviewable/test/lgtm_plus_resolved_discussions_spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/116)
=> Do not approve self-LGTM.

reviewable/lgtm_plus_resolved_discussions.js, reviewable/test/lgtm_plus_resolved_discussions_spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/117)
=> Accept LGTM from approvers as Reviewable moves reviewers to approvers when they are done.

git-review.bash_completion, install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/118)
=> Autocomplete allowed reviewers in git-review.

git-review.bash_completion, git-submit.bash_completion
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/119)
=> Autocomplete instructions for MacOs users.

git-review.bash_completion
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/120)
=> Allow multiple reviewers in autocomplete

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/121)
=> Allow other base branch for integrating in other flows.

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/122)
=> [Git-Review] Implement git-review tool for GitLab as well.

gitlab-cli.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/123)
=> Add documentation forgotten in previous commit.

bin/git-review, git-review.bash_completion
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/124)
=> [Git-Review] Add autocompletion for GitLab projects.

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/125)
=> [Bug Fix] Fix git review to work for gitlab on macos.

bin/git-review
[Bug Fix] Fix git review to work for gitlab on macos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/126)
=> [Review] Allow a custom username when setting a remote branch for review.

.gitignore, install.sh, org.bayes.setup.install.plist
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/130)
=> [Auto-install] Use asyncronous CRON to run install.sh every week.

git-review.bash_completion, git-submit.bash_completion, install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/129)
=> [Autocomplete] Auto-install auto-completion scripts.

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/131)
=> [Anacron] Avoid outputing grep result.

bin/git-rebase-last, git-rebase-last.bash_completion
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/128)
=> [Rebase last] Add a script to rebase last commit of a branch onto another one.

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/132)
=> [Clean Git] Keep only the tip of master branch in directory

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/133)
=> [BugFix] Fix symlink to completion files for MacOS users.

.circleci/config.yml, docker-compose.yml, reviewable/Dockerfile, reviewable/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/135)
=> [Dep Upgrade] Upgrade to eslint v6+ and fix config.

bin/git-review, bin/git-submit
https://github.blog/changelog/2020-05-19-pull-request-retargeting/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/136)
=> [Review] Search for the best base branch now that GitHub retarget PRs.

reviewable/lgtm_plus_resolved_discussions.js, reviewable/test/lgtm_plus_resolved_discussions_spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/138)
=> Cancel LGTM approval for reviewable on :lgtm_cancel:

common-installs/github_tools.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/137)
=> Fix quotes to do string interpolation.

reviewable/lgtm_plus_resolved_discussions.js, reviewable/test/lgtm_plus_resolved_discussions_spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/141)
=> [Reviewable] Use lodash, rather than underscore (that's what Reviewable uses anyway)

common-installs/mac_setup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/140)
=> [Mac] Add useful packages for Mac users.

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/139)
=> [Mac] Add .bashrc sourcing for Mac users when needed.

common-installs/mac_setup.sh
[Mac] Add useful packages for Mac users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/142)
=> [Mac] Use pyenv for best python versionning.

common-installs/mac_setup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/145)
=> [Mac] Add documentation when prompting for new packages install.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/147)
=> [Git] Update the git scripts to use hub api for Github API authentication.

common-installs/mac_setup.sh
[Mac] Add useful packages for Mac users.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/144)
=> [Mac] Suggest bash-completion for mac users.

common-installs/pip_setup.sh, install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/146)
=> [Python] Add linters installation for python code.

common-installs/mac_setup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/148)
=> [Clean Code] Drop unused apps and packages.

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/150)
=> [Clean code] added an arg base branch

.circleci/config.yml, git-custom-commands-test/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/153)
=> [CI] Drop unnecessary docker-compose-up-remote-env

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/154)
=> [Clean code] Update to use default branch instead of master in git review

.circleci/config.yml, README.md, bin/git-rebase-last, git-review.bash_completion, install.sh, man/man1/git-submit.1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/156)
=> [Clean Code] Replace master in favor of main

bin/git-submit, git-custom-commands-test/features/git-submit.feature, git-custom-commands-test/features/steps.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/151)
=> [Clean Code] Update to use default branch instead of master in git submit

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/158)
=> [Install] Allow install to update to the tip of the main branch everytime.

docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/161)
=> Mount tested binaries in docker volumes so that one can test them without rebuilding the container entirely

bin/git-submit, git-custom-commands-test/features/git-submit.feature, git-custom-commands-test/features/steps.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/160)
=> [Fix] Correct git submit when rev-parse exits with an error

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/166)
=> [Submit] Go back to initial branch if anything goes wrong.

bin/git-submit, install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/165)
=> [Submit] Use pull-request show command from hub CLI.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/168)
=> [Bug Fix] Avoid output from checkout to interfere with PR number.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/167)
=> [Submit] Allow to submit and forget, if CI is green.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/169)
=> [Submit] Make sure hub is available when we use it.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/174)
=> [Clean Code] Clear output of git-submit script of useless messages.

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/177)
=> [Bug Fix] Avoid early pipe cancellation between brew and grep in install script.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/175)
=> [Bug Fix] Make sure GIT_SUBMIT_AUTO_MERGE doesn't interfere with normal submit.

common-installs/pip_setup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/178)
=> [Install] Don't ask to install already installed python libs.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/171)
=> [Submit] Do not try to enable auto-merge if not available.

hooks/commit-msg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/179)
=> [Fix] Update commit-msg hook to account for the fact that the input is a file name.

hooks/commit-msg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/176)
=> [Hooks] Allow multiple issue references in commit message hook.

hooks/commit-msg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/180)
=> [Clean Code] Use named regexes in commit message hook for clarity.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/181)
=> [Hooks] Add a pre-commit hook for circleCI config.

hooks/commit-msg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/182)
=> [Bug Fix] Various fixes on the commit message hook.

common-installs/pip_setup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/183)
=> [Clean Code] Do not show the pip version in stdout.

bin/git-rebase-last
This avoids a specific main or master reference.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/186)
=> [Rebase Last] Rebase onto origin's head instead of master.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/188)
=> [Easy Dev] Limit the number of requests to Github's API in git-submit.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/190)
=> [Bug Fix] Fetch before checking remote heads.

hooks/commit-msg
Comments in the commit message file don't make it to the final commit
message, so we can accept them even if they are long.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/187)
=> [Commit Message Hook] Accept long lines that are commented.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/189)
=> [Easy Dev] Check whether the PR is already auto-merging.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/191)
=> [Submit] Add a check for auto-delete of merged branch.

.circleci/config.yml, docker-compose.yml, git-hooks-test/Dockerfile, git-hooks-test/features/commit-msg.feature, git-hooks-test/features/steps.rb, git-hooks-test/features/support/aruba.rb, git-hooks-test/features/support/env.rb
wip
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/192)
=> [Tests] Setup a test environment for hooks.

git-hooks-test/features/commit-msg.feature, hooks/commit-msg
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/193)
=> [Hooks] Ensure the topic is Title Cased.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/194)
=> [Bug Fix] Output warning to stderr.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/198)
=> Set up PR_INFO even if CI status is successful.

bin/echo_with_colors.sh, bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/195)
=> [Submit] Add color to output.

man/man1/git-review.1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/197)
=> [Review] Add a man page for git-review.

bin/git-review, man/man1/git-review.1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/196)
=> [Review] Allow auto-submitting a review.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/199)
=> [Bug Fix] Update the condition to show the auto-delete warning.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/202)
=> [Clean Code] Parse options systematically in git submit.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/201)
=> [Submit] Use REST API to update the branch-deletion setting.

bin/git-submit, man/man1/git-submit.1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/200)
=> [Submit] Allow to recreate a deleted branch from origin.

git-submit.bash_completion
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/203)
=> [Auto-Complete] Auto-completion for git-submit with options.

bin/git-submit, man/man1/git-submit.1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/204)
=> [Submit] Abort auto-merge request.

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/205)
=> Do not ask the auto-submit question on `git review -s`.

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/208)
=> [Easy Dev] Allow using several options at once.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/211)
=> [Submit] Give link to setup auto-merge on repository.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/212)
=> [Auto-merge] Add comments in auto-merging PRs.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/215)
=> [Small Fix] Drop output from GraphQL comment deletion.

bin/git-review.py, common-installs/pip_setup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/213)
=> [Python] Use python for git review script.

bin/git-review.py, common-installs/pip_setup.sh, install.sh
This is useful for git-review, in particular.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/214)
=> [Auto-complete] Add auto-completion for python scripts.

.circleci/config.yml, README.md, bin/git-rebase-last, git-review.bash_completion, install.sh, man/man1/git-submit.1
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/228)
=> [Master Main] Update repo to have ‘main‘ as the default branch.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/232)
=> [Bug Fix] Base is a remote branch and may not exist locally.

bin/git-review.py
Fix #220
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/234)
=> [Python] Show available branches for review.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/237)
=> [Clean Code] Cache branch getting functions.

bin/git-review, git-review.bash_completion
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/239)
=> [Python] Enable Python review as an experimental feature.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/231)
=> [Clean Code] Use classes for platform requests.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/233)
=> [Clean Code] Cache the review platform.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/236)
=> [Review] Allow multiple reviewers from Python script.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/235)
=> [Complete] Add auto-completion for reviewers in python review script.

common-installs/pip_setup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/240)
=> [Easy Dev] Check if unidecode is installed before installing it.

bin/git-review
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/241)
=> [Bug Fix] Don't use a relative link to python script.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/242)
=> [Review] Browse directly to reviewable.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/246)
=> [Bug Fix] Show prepared errors without their stacktrace.

common-installs/mac_setup.sh, install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/244)
=> [Auto-Completion] Use bash-completion@2 when relevant.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/247)
=> [Clean Code] Use a specific type for errors.

bin/git-review.py, common-installs/pip_setup.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/256)
=> [Clean Code] Remove dependency to unidecode.

bin/git-review.py
Fix #225
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/252)
=> [Review] Add the default review feature.

GIT_WORKFLOW_README.md, bin/git-review.py, install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/254)
=> [Reviewers] Request reviews from engineers only.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/257)
=> [Bug Fix] Account for origin/HEAD not to be defined.

git-review.bash_completion
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/259)
=> [Bug Fix] Use a POSIX-compliant sed syntax in autocompletion script.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/261)
=> [Bug Fix] Don't merge on a branch containing HEAD.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/260)
=> [Bug Fix] Don't push on no changes.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/258)
=> [Clean Code] Create a review if one doesn't already exists only.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/250)
=> [Review] Add reviewers on 'git review -f'.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/262)
=> [Bug Fix] Fix split of hub pr list.

reviewable/lgtm_plus_resolved_discussions.js, reviewable/test/lgtm_plus_resolved_discussions_spec.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/253)
=> [Reviewable] Await a review only from a requested reviewer.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/264)
=> [Zube] Add zube label on in-review issues.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/248)
=> [Clean Code] Use generic message on NotImplementedErrors.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/249)
=> [Review] Add auto-complete for 'git review --browse'.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/265)
=> [Review] Automatically assign a reviewer.

bin/git-review.py, install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/266)
=> [Config] Use git config to store values, instead of environment.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/269)
=> [Bug Fix] Do not break on missing argcomplete.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/267)
=> [Clean Code] Move hub api cache mechanism to _run_hub.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/270)
=> [Small Fix] Fix formatting PR number as it's a string already.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/272)
=> [Bug Fix] Separate assignement and request when adding reviewers.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/268)
=> [Clean Code] Use JSON instead of string parsing for review number.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/273)
=> [Doc] Clean documentation on reviewers argument.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/275)
=> [Caching] Bust hub API cache with an option.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/274)
=> [Clean Code] Update reviewers only when needed.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/276)
=> [Review] Deprecate the --force option.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/278)
=> [Bug Fix] Don't serialize sets.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/280)
=> [Bug Fix] Do not warn for no auto-merge when the merge is synchronous.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/279)
=> [Bug Fix] Ensure git-config calls are get or set.

reviewable/lgtm_plus_resolved_discussions.js, reviewable/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/281)
=> [Bug Fix] Revert to underscore indexBy instead of lodash keyBy.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/277)
=> [Small Fix] stringify number from Github API.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/286)
=> [Bug Fix] Find PR when base is not main.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/283)
=> [Clean Code] Use named arguments when passing parsed args.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/285)
=> [Clean Code] Use generic methods for git config.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/284)
=> [Review] Connect reviews to Lucca.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/282)
=> [Review] Add a --new option.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/287)
=> [Lucca] Disable the Lucca link to review by default.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/289)
=> [Bug Fix] Fix base computation.

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/290)
=> [Install] Use a cleaner command to check for hub setup.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/291)
=> [Lucca] Choose email from available ones.

bin/git-review.py
This avoids having the requested reviewers
removed fron the PR once it's been reviewed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/292)
=> [Review] Assign engineers to PRs.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/293)
=> [New Branch] Use counter instead of timestamp for new branches.

bin/git-submit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/294)
=> [Bug Fix] Push changes before submitting.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/296)
=> [Bug Fix] Allow adding an auto-reviewer next to deterministic ones.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/295)
=> [Bug Fix] Switch between engineers and non-engineers assignments.

git-submit.bash_completion
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/297)
=> Fix `git submit -a` completion.

.circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/299)
=> [CI] Add a ping in slack at the end of CI.

install.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/298)
=> Install autocomplete scripts in a user-specific folder.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/301)
=> [Clean Code] Drop dead code, and clean some typing.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/300)
=> [Bug Fix] Ensure the newly created branch name doesn't already exist.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/304)
=> [Clean Code] Use a flag for auto, while there's only one auto mode.

.circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/303)
=> [Clean Code] Update the ping command, now that docker base is updated.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/302)
=> [Bug Fix] Do not update assignees when updating reviewers.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/305)
=> Show the pre-commit warning if circleci is missing.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/306)
=> [Lucca] Auto-send to someone available as soon as possible.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/307)
=> [Small Fix] Stop comparing github handles with lucca emails.

bin/git-review, bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/308)
=> [Easy Dev] Propagate the xtrace (bash -x) to git-review.py.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/310)
=> [Review Hook] Add whitespace between message and review-hook text.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/312)
=> [Bug Fix] Account for Lucca users without an email.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/314)
=> [Small Fix] Use the right config key for lucca emails.

reviewable/lgtm_plus_resolved_discussions.js, reviewable/package.json
Thanks to https://github.com/Reviewable/Reviewable/issues/844
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/315)
=> Use lodash4.

bin/git-review.py, git-custom-commands-test/features/git-review.feature, git-custom-commands-test/features/steps.rb
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/318)
=> [Tests] First test for git-review.py.

bin/git-submit, bin/git-submit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/320)
=> [Bug Fix] Update merge status after github API change.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/336)
=> [Review] More generic way to get the Github username.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/338)
=> [Review] Drop the git-review-hook on error.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/337)
=> [Review] Account for windows in --browse.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/339)
=> [Clean Code] Prepare the precommit hook for multiple validators.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/340)
=> [Hooks] Add a pre-commit hook about Bazel BUILD files.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/341)
=> [Clean Code] Allow disabling pre-commit hooks.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/343)
=> [Bug Fix] Use extended regex in sed for bazel git hook.

bin/git-submit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/342)
=> [Submit] Add the --rebase option.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/344)
=> [Hooks] Run Bazel locally on pre-commit hook.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/346)
=> [Hooks] Separate BUILD files check with Bazel tree check.

bin/git-review.py, bin/git-submit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/352)
=> [Review] Comment on PR when it is auto-assigned.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/354)
=> [Hooks] Ensure we add a funding link to our npm repos.

bin/git-submit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/356)
=> [Submit] Be clearer about already-enabled auto-merge.

bin/git-submit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/357)
=> [Bug Fix] Make sure a failed rebase stops the submit script.

bin/git-submit.py, git-submit.bash_completion
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/358)
=> [Submit] Add auto-completion to python git-submit.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/360)
=> [Clean Code] Fix mypy issues for git-review.

bin/git-submit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/359)
=> [Autocomplete] Add autocompletion for branch and username in git-submit.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/361)
=> [Review] Ensure new branch name is not conflicting with a local branch.

reviewable/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/364)
=> Add funding information to our package.json.

bin/git-review.py, bin/git-submit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/362)
=> Add cache behaviour to git-submit.

bin/git-submit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/366)
=> [Clean Code] Use streamed output from subprocess when useful.

bin/git-submit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/368)
=> [Clean Code] Select the local default branch faster.

docker-compose.yml, git-custom-commands-test/Dockerfile, git-hooks-test/Dockerfile, git-hooks-test/features/commit-msg.feature, git-hooks-test/features/steps.rb, hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/363)
=> [Clean Code] Use python tests for pre-commit hook.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/369)
=> [Hooks] Add a hook about files not in Bazel.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/371)
=> [Hooks] Allow pre-commit hook to show why some hooks were skipped.

git-hooks-test/features/pre-commit.feature, hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/370)
=> [Hooks] Ignore stdlib imports in bazel import diffs.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/372)
=> [Clean Code] Show better results on the bazel files hook.

git-hooks-test/Dockerfile, git-hooks-test/features/pre-commit.feature, git-hooks-test/features/steps.rb, hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/374)
=> [Hooks] Do not check empty init files in bazel diffs.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/373)
=> [Hooks] Test for node import changes in Bazel.

git-hooks-test/features/pre-commit.feature, hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/375)
=> [Bug Fix] Allow new files to be added to Bazel.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/377)
=> [Clean Code] Use classes for differentiating the files we are parsing.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/378)
=> [Clean Code] Use a factory to determine the relevant parser.

bin/git-submit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/376)
=> [Submit] Allow to continue on a pending rebase.

bin/git-submit.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/379)
=> [Small Fix] Do not fail when submitting using GitHub API.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/380)
=> [Small Fix] Make the matches work globally.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/381)
=> [Hooks] Add a line number reference inside the build file.

git-rebase-last.bash_completion
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/383)
=> [rebase-last] Allow remote reference for rebase-last base.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/385)
=> [Bug Fix] Do not call 3rd party program tests if they are not installed.

bin/git-review.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/387)
=> [Git Review] Handle repos with more than 30 PRs open.

hooks/pre-commit
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/bayes-developer-setup/391)
=> [Hooks] Check direct re-exports in typescript files.
